<?php 
function current_posts_help($path, $arg){

switch ($path){
	
	case "admin/help#current_posts":
		return '<p>' . t("Displays links to nodes created on this date"). '</p>';
		break;
}
	

}



?>

<?php
/**
 * Implements hook_block_info().
 */
function current_posts_block_info() {
  $blocks['current_posts'] = array(
    // The name that will appear in the block list.
    'info' => t('Current posts'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}
?>


<?php

function current_posts_contents(){
	
	//this function gets today's date
	$today= getdate();

	//gets the date from a week ago

	$start_time=mktime(0,0,0, $today['mon'], ($today['mday']-7), $today['year']);

	//gets posts from a week ago to now

	$end_time=time();

	//uses db API to get current posts

	$query= db_select('node', 'n')
		->fields('n', array('nid', 'title', 'created'))
		->condition('status', 1) //already published
		->condition('created', array($start_time, $end_time), 'BETWEEN')
		->orderBy('created', 'DESC') //gives em by most recent entry first
		->execute();
	return $query;
}
?>

<?php
function current_posts_block_view($delta=''){
	
	switch ($delta){

		case 'current_posts':
			$block['subject']= t('Current posts');
			if (user_access('access content')){
			//retrieve the data
			$result= current_posts_contents();
			//array for rendering
			$items=array();
			//iterate over result and format as links

			foreach($result as $node){
				$items[]=array(
					'data'=>l($node->title, 'node/' . $node->nid),
				);
			}

			//if there is no content in the last week
			if (empty($items)){
				$block['content']= t('No posts available');
			}
			else{
				$block['content']=theme('item_list', array(
					'items' => $items));
			}

			}
			return $block;
	}
}
?>











